FROM kalilinux/kali-last-release

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    python3 \
    python3-pip \
    clang-16 \
    llvm-16 \
    llvm-16-dev \
    llvm-16-runtime \
    llvm-16-tools \
    libclang-16-dev \
    libclang-common-16-dev \
    libclang-cpp16 \
    libllvm16 \
    afl++ \
    && rm -rf /var/lib/apt/lists/*

# Set up VMF
WORKDIR /usr/local/src/VaderModularFuzzer
COPY . .
RUN mkdir -p build && \
    cd build && \
    cmake .. && \
    make -j$(nproc) && \
    make install

# Set working directory
WORKDIR /usr/local/src/VaderModularFuzzer
