FROM quay.io/centos/centos:stream8 as deps

# Update mirror URLs to use CentOS Stream 8
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
    dnf clean all && \
    dnf makecache

# General dependencies
RUN  dnf install --assumeyes \
        ca-certificates \
        libcurl-minimal \
        gdb \
        git \
        gnupg

# Install Python dependencies
RUN dnf install --assumeyes \
        python3 \
        python3-pip \
        python3-devel \
        gcc \
        gcc-c++ \
        make \
        cmake \
        ninja-build \
        clang \
        clang-devel \
        llvm \
        llvm-devel \
        zlib-devel \
        ncurses-devel \
        sqlite-devel \
        readline-devel \
        tk-devel \
        gdbm-devel \
        db4-devel \
        libpcap-devel \
        xz-devel \
        expat-devel \
        bzip2-devel \
        openssl-devel \
        libffi-devel

# Install AFL++
FROM deps as aflpp
RUN git clone https://github.com/AFLplusplus/AFLplusplus.git /usr/local/src/AFLplusplus && \
    cd /usr/local/src/AFLplusplus && \
    make source-only && \
    make install

# Install VMF
FROM deps as vmf
ARG VMF_REPO=https://github.com/npe9/VaderModularFuzzer.git
RUN git clone ${VMF_REPO} /usr/local/src/VaderModularFuzzer && \
    cd /usr/local/src/VaderModularFuzzer && \
    pip3 install -r requirements.txt && \
    pip3 install -e .

WORKDIR /usr/local/src/VaderModularFuzzer
    