FROM ubuntu:22.04 AS deps

RUN  apt-get update \
     && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends --fix-missing \
       ca-certificates \
       curl \
       gdb \
       git \
       gnupg \
       lsb-core \
       lsb-release \
       zip

# Configure core dumps
RUN echo "core" > /proc/sys/kernel/core_pattern || true

# Add LLVM repository
RUN curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor -o /usr/share/keyrings/llvm-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/llvm-archive-keyring.gpg] http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main" > /etc/apt/sources.list.d/llvm.list

RUN  apt-get update \
     && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --fix-missing \
       graphviz \
       clang-15 \
       clang \
       doxygen \
       libcurl4-openssl-dev \
       llvm-15 \
       llvm-15-dev \
       lld-15 \
       llvm \
       lld \
       python3-dev \
       python3-pip \
       python3-setuptools \
       build-essential \
       cmake \
       afl++ \
       afl++-clang

ENV  LLVM_CONFIG=llvm-config-15

# No need for AFL++ build stage since we're using the package
FROM deps

FROM deps AS vmf

# Clone, build, install VMF
RUN set -ex \
    && cd /usr/local/src \
    && mkdir vmf \
    && git clone --depth 1 https://github.com/draperlaboratory/vadermodularfuzzer.git vmf \
    && cd vmf \
    && mkdir -p build \
    && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. \
    && make -j \
    && make install \
    && set +ex
