name: CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vadermodularfuzzer

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_name: [klee, u20, u22, centos8, centos9, kali]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/Dockerfile.${{ matrix.image_name }}
          build-args: |
            VMF_REPO=https://github.com/${{ github.repository }}.git
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Deploy to production
        id: deploy
        run: |
          # Add your deployment steps here
          # This could include:
          # - Deploying to cloud services
          # - Updating container orchestration
          # - Running database migrations
          echo "Deployment steps to be implemented"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.deb
            build/*.rpm
            build/*.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 