name: CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vadermodularfuzzer

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        image_name: [klee, u20, u22, centos8, centos9, kali]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download packages from CI
        uses: actions/download-artifact@v4
        with:
          name: packages-${{ github.sha }}
          path: build/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/Dockerfile.${{ matrix.image_name }}
          build-args: |
            VMF_REPO=https://github.com/${{ github.repository }}.git
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.deb
            build/*.rpm
            build/*.pkg.tar.zst
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Package Repositories
        run: |
          # Add your package repository publishing logic here
          # This could include:
          # - Publishing to Debian repository
          # - Publishing to RPM repository
          # - Publishing to Arch Linux repository
          echo "Package publishing steps to be implemented" 