name: CD

on:
  push:
    branches:
      - main
      - fix/workflow-trigger  # Branch for testing CD workflow
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-22.04
    # Permissions required for:
    # - contents:write: Creating and pushing tags
    # - packages:write: Publishing Docker images to GHCR
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set sanitized tag
      id: set_tag
      run: |
        SANITIZED_TAG=$(echo "${{ github.ref_name }}" | tr '/' '-')
        echo "tag=$SANITIZED_TAG" >> $GITHUB_OUTPUT

    - name: Create Git tag
      if: github.ref_type != 'tag'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        TAG="v$(date +%Y%m%d)-$(git rev-parse --short HEAD)"
        git tag -a "$TAG" -m "Release $TAG"
        git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git "$TAG"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: dockerfiles/Dockerfile.klee
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/vadermodularfuzzer:${{ steps.set_tag.outputs.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          WORKDIR=/usr/local/src/VaderModularFuzzer

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: |
          build/vader-*.tar.gz
          build/vader-*.zip
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: build-and-publish
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to production
      run: |
        # Add your deployment steps here
        # This could include:
        # - Deploying to cloud services
        # - Updating container orchestration
        # - Running database migrations
        echo "Deployment steps would go here" 