name: VMF CD Pipeline

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and Publish Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfiles/Dockerfile.u22
        push: true
        tags: |
          ghcr.io/draperlaboratory/vadermodularfuzzer:latest
          ghcr.io/draperlaboratory/vadermodularfuzzer:${{ github.ref_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: |
          build/vader-*.tar.gz
          build/vader-*.zip

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: build-and-publish
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to production
      run: |
        # Add your deployment steps here
        # This could include:
        # - Deploying to cloud services
        # - Updating container orchestration
        # - Running database migrations
        echo "Deployment steps would go here" 