name: CD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          vader/vader:latest
          vader/vader:${{ github.ref_name }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: |
          build/vader-*.tar.gz
          build/vader-*.zip

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: build-and-publish
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to production
      run: |
        # Add your deployment steps here
        # This could include:
        # - Deploying to cloud services
        # - Updating container orchestration
        # - Running database migrations
        echo "Deployment steps would go here" 