name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Create fuzz_output directory
        run: mkdir -p fuzz_output
      
      - name: Run tests with Docker
        run: |
          docker run --privileged \
            -v $(pwd)/fuzz_output:/fuzz_output \
            -e VMF_TEST_TIMEOUT=300 \
            ghcr.io/${{ github.repository }}:latest \
            bash -c "cd /usr/local/test && cmake -B build -S . && cd build && make -j && ctest --output-on-failure"
      
      - name: Verify Fuzzing Results Directory
        run: |
          if [ ! -d "fuzz_output" ]; then
            echo "Error: fuzz_output directory does not exist"
            exit 1
          fi
          echo "Contents of fuzz_output directory:"
          ls -la fuzz_output
      
      - name: Upload fuzzing results
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-results
          path: fuzz_output/
          if-no-files-found: warn 