name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build and test with Docker
      run: |
        set -e
        docker build -t vader-modular-fuzzer .
        docker run -v $(pwd)/fuzz_output:/app/fuzz_output vader-modular-fuzzer /bin/bash -c "
          set -e
          mkdir -p fuzz_output
          timeout 300 ./build/bin/unit_tests
          timeout 300 ./build/bin/fuzzing_tests
        "

    - name: Upload fuzzing results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: fuzzing-results
        path: fuzz_output/
        retention-days: 7 