name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test Vader Modular Fuzzer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image and Run Tests
      run: |
        set -e
        docker build -t vader-modular-fuzzer -f dockerfiles/Dockerfile.u22 .
        docker run --privileged -v $(pwd):/app -v $(pwd)/fuzz_output:/app/fuzz_output vader-modular-fuzzer /bin/bash -c "
          set -e
          cd /app
          mkdir -p fuzz_output
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make -j$(nproc)
          echo core > /proc/sys/kernel/core_pattern
          ctest --output-on-failure
        "

    - name: Archive Fuzzing Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: fuzzing-results
        path: fuzz_output/
        retention-days: 7 