name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build and test with Docker
      run: |
        # Build the Docker image
        docker build -t vmf-test -f dockerfiles/Dockerfile.u22 .
        
        # Run unit tests
        docker run --rm vmf-test bash -c "cd /usr/local/src/vmf/build && ctest --output-on-failure"
        
        # Run fuzzing tests
        docker run --rm -v $(pwd):/workdir vmf-test bash -c "
          cd /workdir &&
          # Build test binaries
          cd test/haystackSUT && make &&
          cd ../magicBytesSUT && make &&
          cd ../.. &&
          # Run fuzzing tests
          vmf fuzz -c test/haystackSUT/haystack_stdin.yaml -o fuzz_output/haystack_stdin &&
          vmf fuzz -c test/haystackSUT/haystack_file.yaml -o fuzz_output/haystack_file &&
          vmf fuzz -c test/magicBytesSUT/magicbytes.yaml -o fuzz_output/magicbytes
        " 